//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.AMIS.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Mã nhân viên&quot;.
        /// </summary>
        public static string EmployeeCode {
            get {
                return ResourceManager.GetString("EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra lại dữ liệu!.
        /// </summary>
        public static string USerMsg_BadRequest {
            get {
                return ResourceManager.GetString("USerMsg_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu thất bại!.
        /// </summary>
        public static string UserMsg_Delete_Fail {
            get {
                return ResourceManager.GetString("UserMsg_Delete_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu thành công!.
        /// </summary>
        public static string UserMsg_Delete_Success {
            get {
                return ResourceManager.GetString("UserMsg_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại!.
        /// </summary>
        public static string UserMsg_Duplicate_EmployeeCode {
            get {
                return ResourceManager.GetString("UserMsg_Duplicate_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã tồn tại!.
        /// </summary>
        public static string UserMsg_Duplicate_Email {
            get {
                return ResourceManager.GetString("UserMsg_Duplicate_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã tồn tại!.
        /// </summary>
        public static string UserMsg_Duplicate_PhoneNumber {
            get {
                return ResourceManager.GetString("UserMsg_Duplicate_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ MISA!.
        /// </summary>
        public static string UserMsg_Exception {
            get {
                return ResourceManager.GetString("UserMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới dữ liệu thành công!.
        /// </summary>
        public static string UserMsg_Insert_Created {
            get {
                return ResourceManager.GetString("UserMsg_Insert_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có bản ghi nào được thêm mới!.
        /// </summary>
        public static string UserMsg_Insert_Success {
            get {
                return ResourceManager.GetString("UserMsg_Insert_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được để trống!.
        /// </summary>
        public static string UserMsg_Require_EmployeeCode {
            get {
                return ResourceManager.GetString("UserMsg_Require_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị không được để trống!.
        /// </summary>
        public static string UserMsg_Require_DepartmentName {
            get {
                return ResourceManager.GetString("UserMsg_Require_DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên không được để trống!.
        /// </summary>
        public static string UserMsg_Require_EmployeeName {
            get {
                return ResourceManager.GetString("UserMsg_Require_EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa dữ liệu thất bại!.
        /// </summary>
        public static string UserMsg_Update_Fail {
            get {
                return ResourceManager.GetString("UserMsg_Update_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa dữ liệu thành công!.
        /// </summary>
        public static string UserMsg_Update_Success {
            get {
                return ResourceManager.GetString("UserMsg_Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string VIE_Gender_Name_Female {
            get {
                return ResourceManager.GetString("VIE_Gender_Name_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string VIE_Gender_Name_Male {
            get {
                return ResourceManager.GetString("VIE_Gender_Name_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string VIE_Gender_Name_Other {
            get {
                return ResourceManager.GetString("VIE_Gender_Name_Other", resourceCulture);
            }
        }
    }
}
